# # REFERENCES
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NjI4MzYyNzR9.aiWltD42EC4W3SZdI0OSbrTRjCZjA2vBBfz7Fwh3iFk

# # PRODUCT ACTIONS ------------------------
### Product Index Action
GET http://localhost:3000/products.json

### Product Show Action
GET  http://localhost:3000/products/5.json

### Product Create Action
POST http://localhost:3000/products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "test name 2",
  "price": 2.00,
  "description": "test description 2",
  "inventory": 2,
  "supplier_id": 3
}

### Product Update Action
PATCH http://localhost:3000/products/1.json
Content-Type: application/json

{
  "name": "test update name",
  "price": 1,
  "image_url": "image not found",
  "description": "test update description",
  "inventory": 1
}

### Product Delete/Destroy Action
DELETE  http://localhost:3000/products/5.json


# # SUPPLIER ACTIONS ----------------------------
### Supplier Index Action
GET http://localhost:3000/suppliers.json


# # USER ACTIONS -------------------------------
### User Create Action
POST http://localhost:3000/users.json 
Content-Type: application/json

{
  "name": "grace",
  "email": "grace@email.com",
  "password": "password",
  "password_confirmation": "password"
}

# # SESSION ACTIONS -----------------------
### Session Create Action (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "grace@email.com",
  "password": "password"
}

# # ORDER ACTIONS ---------------------------
### Order Create Action
POST http://localhost:3000/orders.json 
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NjI4MjY5NjF9.gP12vP7P0rVibLP8nYVUjrQftgIY8T3zYWzZWNXNgsk
Content-Type: application/json

{
  "product_id": 3,
  "quantity": 2
}

### Order Show Action
GET http://localhost:3000/orders/3.json 
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NjI4MjY5NjF9.gP12vP7P0rVibLP8nYVUjrQftgIY8T3zYWzZWNXNgsk

### orders show only shows 1st order and can still belong to any user_id

### Order Index Action
GET http://localhost:3000/orders.json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NjI4MjY5NjF9.gP12vP7P0rVibLP8nYVUjrQftgIY8T3zYWzZWNXNgsk

