# # REFERENCES
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NjMxODM0Mjd9.20co7MMNQBGOw6pBXKbfYW9r4Kgb95OqScPog7IVp4o

# # PRODUCT ACTIONS ------------------------
### Product Index Action
GET http://localhost:3000/products.json?category=Accessories

### Product Show Action
GET  http://localhost:3000/products/5.json

### Product Create Action
POST http://localhost:3000/products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "test name 2",
  "price": 2.00,
  "description": "test description 2",
  "inventory": 2,
  "supplier_id": 3
}

### Product Update Action
PATCH http://localhost:3000/products/8.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "test update name",
  "price": 1,
  "image_url": "image not found",
  "description": "test update description",
  "inventory": 1
}

### Product Delete/Destroy Action
DELETE  http://localhost:3000/products/6.json
Authorization: Bearer {{jwt}}


# # SUPPLIER ACTIONS ----------------------------
### Supplier Index Action
GET http://localhost:3000/suppliers.json


# # USER ACTIONS -------------------------------
### User Create Action
POST http://localhost:3000/users.json 
Content-Type: application/json

{
  "name": "mark",
  "email": "mark@email.com",
  "password": "password",
  "password_confirmation": "password"
}

# # SESSION ACTIONS -----------------------
### Session Create Action (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "mark@email.com",
  "password": "password"
}

# # ORDER ACTIONS ---------------------------
### Order Create Action
POST http://localhost:3000/orders.json 
Authorization: Bearer {{jwt}}

### Order Show Action
GET http://localhost:3000/orders/3.json 
Authorization: Bearer {{jwt}}

### Order Index Action
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}


# # CARTEDPRODUCT ACTIONS ------------------------
### CartedProduct Index Action
GET http://localhost:3000/carted_products.json
Authorization: Bearer {{jwt}}


### CartedProduct Create Action
POST http://localhost:3000/carted_products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "user_id": 4,
  "product_id": 3,
  "quantity": 2
}

### CartedProduct Delete Action
DELETE http://localhost:3000/carted_products/5.json
Authorization:  Bearer {{jwt}}

### NOTES: