### Product Index Action
GET http://localhost:3000/products.json

### Product Show Action
GET  http://localhost:3000/products/5.json

### Product Create Action
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "test name",
  "price": 1.00,
  "description": "test description",
  "inventory": 1
}

### Product Update Action
PATCH http://localhost:3000/products/1.json
Content-Type: application/json

{
  "name": "test update name",
  "price": 1,
  "image_url": "image not found",
  "description": "test update description",
  "inventory": 1
}

### Product Delete/Destroy Action
DELETE  http://localhost:3000/products/5.json


### Supplier Index Action
GET http://localhost:3000/suppliers.json